/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as AuthImport } from './pages/_auth'
import { Route as IndexImport } from './pages/index'

// Create Virtual Routes

const AuthIndexLazyImport = createFileRoute('/auth/')()
const AuthHomeIndexLazyImport = createFileRoute('/_auth/home/')()
const AuthGoalsIndexLazyImport = createFileRoute('/_auth/goals/')()
const AuthBalanceIndexLazyImport = createFileRoute('/_auth/balance/')()
const AuthAboutIndexLazyImport = createFileRoute('/_auth/about/')()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexLazyRoute = AuthIndexLazyImport.update({
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/auth/index.lazy').then((d) => d.Route))

const AuthHomeIndexLazyRoute = AuthHomeIndexLazyImport.update({
  path: '/home/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./pages/_auth/home/index.lazy').then((d) => d.Route),
)

const AuthGoalsIndexLazyRoute = AuthGoalsIndexLazyImport.update({
  path: '/goals/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./pages/_auth/goals/index.lazy').then((d) => d.Route),
)

const AuthBalanceIndexLazyRoute = AuthBalanceIndexLazyImport.update({
  path: '/balance/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./pages/_auth/balance/index.lazy').then((d) => d.Route),
)

const AuthAboutIndexLazyRoute = AuthAboutIndexLazyImport.update({
  path: '/about/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./pages/_auth/about/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/about/': {
      id: '/_auth/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthAboutIndexLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/balance/': {
      id: '/_auth/balance/'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof AuthBalanceIndexLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/goals/': {
      id: '/_auth/goals/'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthGoalsIndexLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/home/': {
      id: '/_auth/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthHomeIndexLazyImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthRoute: AuthRoute.addChildren({
    AuthAboutIndexLazyRoute,
    AuthBalanceIndexLazyRoute,
    AuthGoalsIndexLazyRoute,
    AuthHomeIndexLazyRoute,
  }),
  AuthIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/auth/"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/about/",
        "/_auth/balance/",
        "/_auth/goals/",
        "/_auth/home/"
      ]
    },
    "/auth/": {
      "filePath": "auth/index.lazy.ts"
    },
    "/_auth/about/": {
      "filePath": "_auth/about/index.lazy.ts",
      "parent": "/_auth"
    },
    "/_auth/balance/": {
      "filePath": "_auth/balance/index.lazy.ts",
      "parent": "/_auth"
    },
    "/_auth/goals/": {
      "filePath": "_auth/goals/index.lazy.ts",
      "parent": "/_auth"
    },
    "/_auth/home/": {
      "filePath": "_auth/home/index.lazy.ts",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
