name: Build, push and deploy

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{secrets.DOCKER_REGISTRY}}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}
          tags: |
            type=sha,format=short,prefix=
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
      # - name: executing remote ssh commands using ssh key
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:latest
      #       docker stop landing || true
      #       docker rm landing || true
      #       docker run -d -p:3000:3000 --name=landing ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:latest

      - name: Add job summary
        uses: jazanne/job-summary-action@v1
        with:
          summary: |
            # Сводка сборки
            - Cборку запустил: ${{github.server_url}}/${{github.actor}}

            - Теги:
            ${{ steps.meta.outputs.tags }}

            - Ссылка на сборку: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
